//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: route_guide.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import FlatBuffers

public protocol GRPCFlatBufPayload: GRPCPayload, FlatBufferGRPCMessage {}

public extension GRPCFlatBufPayload {
    init(serializedByteBuffer: inout NIO.ByteBuffer) throws {
        self.init(byteBuffer: FlatBuffers.ByteBuffer(contiguousBytes: serializedByteBuffer.readableBytesView, count: serializedByteBuffer.readableBytes))
    }
    func serialize(into buffer: inout NIO.ByteBuffer) throws {
        let buf = UnsafeRawBufferPointer(start: self.rawPointer, count: Int(self.size))
        buffer.writeBytes(buf)
    }
}
extension Message: GRPCFlatBufPayload {}

/// Usage: instantiate Routeguide_RouteGuideServiceClient, then call methods of this protocol to make API calls.
public protocol Routeguide_RouteGuideService {
  func getFeature(_ request: Message<Point>, callOptions: CallOptions?) -> UnaryCall<Message<Point>, Message<Feature>>
  func listFeatures(_ request: Message<Rectangle>, callOptions: CallOptions?, handler: @escaping (Message<Feature>) -> Void) -> ServerStreamingCall<Message<Rectangle>, Message<Feature>>
  func recordRoute(callOptions: CallOptions?) -> ClientStreamingCall<Message<Point>, Message<RouteSummary>>
  func routeChat(callOptions: CallOptions?, handler: @escaping (Message<RouteNote>) -> Void) -> BidirectionalStreamingCall<Message<RouteNote>, Message<RouteNote>>
}

public final class Routeguide_RouteGuideServiceClient: GRPCClient, Routeguide_RouteGuideService {
    
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the routeguide.RouteGuide service.
  ///
  /// - Parameters:
  ///   - channel: `channel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous unary call to GetFeature.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFeature.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getFeature(_ request: Message<Point>, callOptions: CallOptions? = nil) -> UnaryCall<Message<Point>, Message<Feature>> {
    return self.makeUnaryCall(path: "/routeguide.RouteGuide/GetFeature",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous server-streaming call to ListFeatures.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListFeatures.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func listFeatures(_ request: Message<Rectangle>, callOptions: CallOptions? = nil, handler: @escaping (Message<Feature>) -> Void) -> ServerStreamingCall<Message<Rectangle>, Message<Feature>> {
    return self.makeServerStreamingCall(path: "/routeguide.RouteGuide/ListFeatures",
                                        request: request,
                                        callOptions: callOptions ?? self.defaultCallOptions,
                                        handler: handler)
  }

  /// Asynchronous client-streaming call to RecordRoute.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  public func recordRoute(callOptions: CallOptions? = nil) -> ClientStreamingCall<Message<Point>, Message<RouteSummary>> {
    return self.makeClientStreamingCall(path: "/routeguide.RouteGuide/RecordRoute",
                                        callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous bidirectional-streaming call to RouteChat.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func routeChat(callOptions: CallOptions? = nil, handler: @escaping (Message<RouteNote>) -> Void) -> BidirectionalStreamingCall<Message<RouteNote>, Message<RouteNote>> {
    return self.makeBidirectionalStreamingCall(path: "/routeguide.RouteGuide/RouteChat",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol Routeguide_RouteGuideProvider: CallHandlerProvider {
  func getFeature(request: Message<Point>, context: StatusOnlyCallContext) -> EventLoopFuture<Message<Feature>>
  func listFeatures(request: Message<Rectangle>, context: StreamingResponseCallContext<Message<Feature>>) -> EventLoopFuture<GRPCStatus>
  func recordRoute(context: UnaryResponseCallContext<Message<RouteSummary>>) -> EventLoopFuture<(StreamEvent<Message<Point>>) -> Void>
  func routeChat(context: StreamingResponseCallContext<Message<RouteNote>>) -> EventLoopFuture<(StreamEvent<Message<RouteNote>>) -> Void>
}

extension Routeguide_RouteGuideProvider {
  public var serviceName: String { return "routeguide.RouteGuide" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "GetFeature":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getFeature(request: request, context: context)
        }
      }

    case "ListFeatures":
      return ServerStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listFeatures(request: request, context: context)
        }
      }

    case "RecordRoute":
      return ClientStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.recordRoute(context: context)
      }

    case "RouteChat":
      return BidirectionalStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.routeChat(context: context)
      }

    default: return nil
    }
  }
}
